### ISSUE TITLE
Regex matching

### ISSUE THREAD

**Issue by simonmandlik** [gazorby/fish-abbreviation-tips#25]
**Question**

If the default regex tries to match the first three words besides other things, why the following doesn't work for me?

```
~
❯ git pull origin
fatal: not a git repository (or any of the parent directories): .git

─────
Hint: gll => git pull origin

~
❯ git pull origin master
fatal: not a git repository (or any of the parent directories): .git
```

**Considerations**

I have changed nothing in `config.fish`, apart from 

```
set -x ABBR_TIPS_PROMPT "\n─────\nHint: \e[1m{{ .abbr }}\e[0m => {{ .cmd }}"
```

**Comment by gazorby** [comment]
Hi @simonmandlik! Your example does not fail on my side, is it still an issue for you?

**Comment by simonmandlik** [comment]
No, looks fixed now :)
