### ISSUE TITLE
None of the abbreviations work

### ISSUE THREAD

**Issue by aharo24** [gazorby/fish-abbreviation-tips#28]
Im unsure why, this is the only plug that dont seem to work. Any tips or help? 

![aharo24 2023-01-14 at 4 44 29 PM](https://user-images.githubusercontent.com/52618896/212503366-4d564652-94a6-4a1e-ab78-004bbdefdf2a.png)

**Comment by gazorby** [comment]
Hey @aharo24! Did you set a `ga` abbreviation? This plugin does not creates any abbreviation, but provides tips for existing ones.

**Comment by gazorby** [comment]
Hi @aharo24 latest changes on master should fix your bug, feel free to reopen this if it's still there!
